# -*- coding: utf-8 -*-
"""biloliddin

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eO9aKPiDXgeDhT-xYhrmr9Z7NEolijbC
"""

import pandas as pn
# 1. DataFrame yaratish
data = {
'Ism': ['Ali', 'Vali', 'Sardor', 'Rahimberdi', 'Jamshid', 'Abdurahmon', 'Samandar'],
'Yoshi' : [25, 30, 22,19,35,21,20],
'Shahar': ['Toshkent', 'Samarqand', 'Buxoro','Fargona','jizzax','andijon','namangan'],
}
df = pn.DataFrame(data)
# 2. Ma'lumotlarni ko'rish
print(df)
# 3. Filtrlash
young_people = df[df['Yoshi'] < 30]
print("30 yoshdan kichiklar:\n", young_people)
# 4. O'zgartirish
df['Yoshi'] += 1 # Har bir shaxsning yoshini 1 ga oshirish
print("Yangilangan DataFrame:\n", df)